# Generated by Django 6.0.3 on 2026-03-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('rol', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student'), ('Admin', 'Admin'), ('Visitant', 'Visitant')], default='Student', max_length=30)),
                ('data_naixement', models.DateField()),
                ('tlf', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=20)),
                ('codi', models.CharField(max_length=5)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
